#driver for queue mod
#caden mcarthur
import qmod

def main():
    q = qmod.Queue()
    print(qmod.Queue.size(q),'size')
    q.enqueue('12')
    q.enqueue('3')
    q.enqueue('82')
    q.enqueue('1')
    print('queue size,')
    print(qmod.Queue.size(q),'size')
    print('elements in q')
    
    print(qmod.Queue.show(q))
    print('-----')
    print('dequeue first element entered')
    q.dequeue(0)
    print('-----')
    print('new queue size')
    print(qmod.Queue.size(q),'size')
    print(qmod.Queue.show(q))
    print('-----')
    print('dequeue next new element')
    q.dequeue(0)
    print('-----')
    print(qmod.Queue.show(q))
    print(qmod.Queue.size(q),'size')
    print('-----')
    print('enqueue 100')
    q.enqueue('100')
    print('-----')
    print(qmod.Queue.show(q))
    q.dequeue(0)
    print('dequeue')
    print(qmod.Queue.show(q))
    print('-----')
main()
